export const SET_DATA_TO_STATE = 'SET_DATA_TO_STATE';
export const SET_YEARS_TO_STATE = 'SET_YEARS_TO_STATE';
export const SET_SEGREGATED_DATA_BY_YEAR_TO_STATE = 'SET_SEGREGATED_DATA_BY_YEAR_TO_STATE';
export const CHANGE_ACTIVE_YEAR = 'CHANGE_ACTIVE_YEAR';

